### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by contradirony**

### CODE REVIEW

**Comment by 1twa** [comment]
test

**Comment by 1twa** [comment]
Hi. Thanks for that package.
I observed, that I do not see some of the games that are listed on mb.com in the API.
What might be the reason for that?

**Comment by xanadunf** [comment]
which games do you not see ? I can look into this

**Comment by xanadunf** [comment]
you can write about any issues here https://github.com/xanadunf/matchbook/issues

**Comment by 1twa** [comment]
For example I can not see the games for Soccer, Turkey - Super Lig that 
take place tomorrow (2/4/16).
E.g Eskisehirspor vs. Galatasaray

Am 01.04.2016 um 12:50 schrieb xanadunf:

**Comment by xanadunf** [comment]
See the issues section of this repo for the solution - you just need to change the start_date and end_date parameters of the mb_get_events call 

Agreed it could be made easier to select out markets from different countries ...

**Pull request closed without merging**
